name: Qase Test Run

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Your build and setup steps here

      - name: Run Qase Tests
        uses: qase-tms/qase-cloud-ci-integrations@v1
        with:
          project_code: 'DEMO'
          api_token: ${{ secrets.QASE_API_TOKEN }}
          run_title: 'GitHub Actions Run-1'
          case_ids: '1050'
